# ðŸ“ pubspec.yaml (ì´ íŒŒì¼ ì „ì²´ë¥¼ ë³µì‚¬í•˜ì—¬ ë¶™ì—¬ë„£ìœ¼ì„¸ìš”)

name: chicachew
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  go_router: ^14.1.0
  camera: ^0.11.0+1
  permission_handler: ^11.3.1
  flutter_tts: ^4.0.2
  tflite_flutter: ^0.11.0
  image: ^4.1.7
  flutter_riverpod: ^2.5.1  # (+) ì´ ì¤„ì´ ì¶”ê°€ë˜ì—ˆìŠµë‹ˆë‹¤.
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  provider: ^6.1.2
  path_provider: ^2.1.3
  collection: ^1.18.0
  uuid: ^4.4.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
    - assets/models/
    - assets/mp/
    - assets/